### ISSUE TITLE
cp-scenario does not work properly for Fertilizer industry (process) 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etm-tools#6]
I tried to project a fictional scenario with CCUS technologies on Zuid-Holland.

Original: 1370260
Projected: 1370262

The slider Fertilizer industry (process) is at zero in the projected scenario and instead of on the set value.

![image](https://user-images.githubusercontent.com/19907658/98666805-d2249980-234d-11eb-9713-a8304eb62d6c.png)

notifying @michieldenhaan  
@antw please reassign when appropriate

**Comment by antw** [comment]
This isn't a bug with cp-scenario, so I'll close this issue. You may track progress on the fix in quintel/etsource#2377.
